package org.econocom.geekstagram.comment;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "comment")
public class CommentEntity {

	/**
	 * The database ID, auto generated by Spring through JPA
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	/**
	 * The content of the comment, null not allowed
	 */
	@NotNull
	private String content;

	/**
	 * The timestamp when the comment has been published, null not allowed
	 */
	@NotNull
	private long date;

	/**
	 * Default constructor, needed when dealing with JPA * @constructor
	 */
	public CommentEntity() {
		super();
	}

	/**
	 * Standard constructor
	 * 
	 * @constructor
	 * @param content
	 *            Content of the comment
	 * @param date
	 *            Date of the comment
	 */
	public CommentEntity(String content, long date) {
		super();
		this.content = content;
		this.date = date;
	}

	/**
	 * Id getter
	 * 
	 * @returns The id of the comment
	 */
	public long getId() {
		return id;
	}

	/**
	 * Content getter
	 * 
	 * @returns The content of the comment
	 */
	public String getContent() {
		return content;
	}

	/**
	 * Content setter
	 * 
	 * @param content
	 *            Content of the comment
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * Date getter
	 * 
	 * @returns The date of the comment
	 */
	public long getDate() {
		return date;
	}

	/**
	 * Date setter
	 * 
	 * @param date
	 *            Date of the comment
	 */
	public void setDate(long date) {
		this.date = date;
	}

	public void setId(long id) {
		this.setId(id);

	}

}
